name: Churn Prediction CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  lint:
    name: Format Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black==23.3.0
    
    - name: Run Black formatter
      run: |
        black --check .
        
  build:
    name: Build Docker Image
    needs: lint  # Only run if formatting check passes
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false  # Don't push, just build
        tags: churn-prediction:latest
        outputs: type=docker,dest=/tmp/churn-prediction.tar
    
    # Instead of using the upload-artifact action, let's just print a success message
    - name: Docker build success
      run: |
        echo "Docker image built successfully!"
        echo "Image file: /tmp/churn-prediction.tar"
        ls -la /tmp/churn-prediction.tar